import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client"; // Ensure correct import path

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rabbactor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div>
            {/* Header */}
            {children}
          </div>
          {/* Footer */}
        </UserProvider>
      </body>
    </html>
  );
}
